name: FinSetsForCAP
version: "2024.01-02"
license: "GPL-2.0-or-later"
date: 2024-01-22
description: |
    The elementary topos of (skeletal) finite sets

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

GAP: ">= 4.12.1"

needed-pkgs:
    - name: "CAP"
      version: ">= 2023.12-05"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "CartesianCategories"
      version: ">= 2024.01-05"
      url: "https://homalg-project.github.io/pkg/CartesianCategories"
    - name: "Toposes"
      version: ">= 2024.01-02"
      url: "https://homalg-project.github.io/pkg/Toposes"

www: https://homalg-project.github.io/pkg/FinSetsForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/FinSetsForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FinSetsForCAP/releases/download/v2024.01-02/FinSetsForCAP-2024.01-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/FinSetsForCAP/releases/download/v2024.01-02/FinSetsForCAP-2024.01-02.zip

pdf: https://github.com/homalg-project/FinSetsForCAP/releases/download/v2024.01-02/FinSetsForCAP-2024.01-02-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BMZ22</span>]   <b class='BibAuthor'>Barakat, M., Mickisch, J. and Zickgraf, F.</b>,
     <i class='BibTitle'>FinSetsForCAP, The elementary topos of (skeletal) finite sets,
             Version 2024.01-02</i>
     (<span class='BibYear'>1-22</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/FinSetsForCAP">https://homalg-project.github.io/pkg/FinSetsForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ FinSetsForCAP2024.01-02,
      author =           {Barakat, M. and Mickisch, J. and Zickgraf, F.},
      title =            {{FinSetsForCAP},  The  elementary  topos of (skeletal)
                          finite sets, {V}ersion 2024.01-02},
      month =            {4-},
      year =             {1-22},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/FinSetsForCAP}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{FinSetsForCAP}}},
      printedkey =       {BMZ22}
    }

