name: FinSetsForCAP
version: "2022.05-04"
license: "GPL-2.0-or-later"
date: 2022-05-20
description: |
    The elementary topos of (skeletal) finite sets

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2022.05-06"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "Toposes"
      version: ">= 2022.04-28"
      url: "https://homalg-project.github.io/pkg/Toposes"

www: https://homalg-project.github.io/pkg/FinSetsForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/FinSetsForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FinSetsForCAP/releases/download/v2022.05-04/FinSetsForCAP-2022.05-04.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/FinSetsForCAP/releases/download/v2022.05-04/FinSetsForCAP-2022.05-04.zip

pdf: https://github.com/homalg-project/FinSetsForCAP/releases/download/v2022.05-04/FinSetsForCAP-2022.05-04.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BMZ22</span>]   <b class='BibAuthor'>Barakat, M., Mickisch, J. and Zickgraf, F.</b>,
     <i class='BibTitle'>FinSetsForCAP, The elementary topos of (skeletal) finite sets,
             Version 2022.05-04</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/FinSetsForCAP">https://homalg-project.github.io/pkg/FinSetsForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ FinSetsForCAP2022.05-04,
      author =           {Barakat, M. and Mickisch, J. and Zickgraf, F.},
      title =            {{FinSetsForCAP},  The  elementary  topos of (skeletal)
                          finite sets, {V}ersion 2022.05-04},
      month =            {May},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/FinSetsForCAP}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{FinSetsForCAP}}},
      printedkey =       {BMZ22}
    }

